name: Xcode - Build and Analyze

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Release IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: "git submodule update --init --recursive"
      - name: Build
        run: |
          xcodebuild -verbose -workspace Moonlight.xcodeproj/project.xcworkspace -scheme Moonlight -sdk iphoneos -configuration AppStoreDistribution  archive -archivePath $PWD/build/Moonlight-NE.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
          mkdir -p ./build/IPA && mkdir -p ./build/IPA/Payload
          cp -r ./build/Moonlight-NE.xcarchive/Products/Applications/Moonlight.app ./build/IPA/Payload/Moonlight.app
          cd ./build/IPA && zip -r ../../build/Moonlight.ipa ./Payload/* && cd ../..
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Moonlight-NE nightly artifact
          path: build/Moonlight.ipa
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "build/Moonlight-NE.ipa"
            name: Moonlight-NE#${{ github.ref }}
            body: ${{ github.event.head_commit.message }}
            tag: ${{ github.ref }}
